### ISSUE TITLE
Scrimba video is too small?

### ISSUE THREAD

**Issue by JoeSpizz** [learn-co-curriculum/react-hooks-lecture-videos-intro-to-react#1]
### Canvas Link

https://learning.flatironschool.com/courses/5301/pages/video-introduction-to-react?module_item_id=414053

### Concern

At a few times, the presenter references things (such as at about 2:20 in) that are outside the scrimba display window. And I can't figure out how to expand. 
Similarly, I can't edit the window as it seems I should be able to. 
I fear this might be a local/user error issue but I can't figure it out. 

### Suggested Changes

Might have to re-record? Or have a paragraph explaining scrimba and how to navigate it?

**Comment by lizbur10** [comment]
Hi @JoeSpizz - thanks for bringing this to our attention! This should now be fixed for all videos in this phase, but please let us know if you run into any more problems.

Thanks for contributing to the Flatiron School curriculum 💙
